### ISSUE TITLE
Why don't you publish `.plugin` file?

### ISSUE THREAD

**Issue by bphd** [ONLYOFFICE/plugin-wordpress#6]

**Comment by ShockwaveNN** [comment]
Same as https://github.com/ONLYOFFICE/plugin-highlightcode/issues/37

Issue 55378 in our private issue tracker

**Comment by catbasilio** [comment]
[Fixed](https://github.com/ONLYOFFICE/plugin-wordpress/releases/tag/v1.0.0)
